- hosts: centos
  vars:
    image: idndevops/webcustom
  tasks:
    - name: install docker-py di centos
      yum: 
        name: "{{ item }}"
        state: present
      loop:
        - epel-release
        - python3
        - python3-docker
      when: ansible_facts['os_family'] == "RedHat"

    - name: running container
      docker-container:
        name: docker-ansible
        image: "{{ image }}"
        published_ports:
          - 10000:80
        recreate: yes
        state: started
        restart_policy: always
        pull: yes



